routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route website
Route::get('/', [App\Http\Controllers\WebsiteController::class, 'index'])->name('index');
Route::get('detail/{id}/{slug}', [App\Http\Controllers\WebsiteController::class, 'detail'])->name('detail');
Route::prefix('/customer')->name('customer.')->group(function(){
    Route::post('/create', [App\Http\Controllers\WebsiteController::class, 'createCustomerInformation'])->name('create');
    Route::post('/update', [App\Http\Controllers\WebsiteController::class, 'updateCustomerInformation'])->name('update');
});
Route::get('invoice/{id}', [App\Http\Controllers\WebsiteController::class, 'invoice'])->name('invoice');
// download PDF
Route::get('/downloadPDF/{id}',[App\Http\Controllers\DownloadController::class, 'downloadPDF'])->name('downloadPDF');

Auth::routes();
Route::group(['middleware' => ['auth' ]], function () {
    // Route dashboard
    Route::prefix('/dashboard')->name('dashboard.')->group(function(){
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('index');
    });

    // Route contacts
    Route::prefix('/contacts')->name('contacts.')->group(function(){
        Route::get('/', [App\Http\Controllers\ContactController::class, 'index'])->name('index');
        Route::get('/create', [App\Http\Controllers\ContactController::class, 'create'])->name('create');
        Route::post('/store', [App\Http\Controllers\ContactController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [App\Http\Controllers\ContactController::class, 'show'])->name('show');
        Route::post('/update', [App\Http\Controllers\ContactController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [App\Http\Controllers\ContactController::class, 'delete'])->name('delete');
    });

    // Route product
    Route::prefix('/product')->name('product.')->group(function(){
        Route::get('/', [App\Http\Controllers\ProductController::class, 'index'])->name('index');
        Route::get('/create', [App\Http\Controllers\ProductController::class, 'create'])->name('create');
        Route::post('/store', [App\Http\Controllers\ProductController::class, 'store'])->name('store');
        Route::get('/edit/{id}', [App\Http\Controllers\ProductController::class, 'show'])->name('show');
        Route::post('/update', [App\Http\Controllers\ProductController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [App\Http\Controllers\ProductController::class, 'delete'])->name('delete');
        Route::post('/updateDetail', [App\Http\Controllers\ProductController::class, 'updateDetail'])->name('updateDetail');
    });

    // Route order
    Route::prefix('/order')->name('order.')->group(function(){
        Route::get('/', [App\Http\Controllers\OrderController::class, 'index'])->name('index');
        Route::get('detail/{id}', [App\Http\Controllers\OrderController::class, 'detail'])->name('detail');
        Route::post('/update', [App\Http\Controllers\OrderController::class, 'update'])->name('update');
    });

    Route::post('send-mail', [App\Http\Controllers\MailController::class, 'sendMailInvoice'])->name('sendMailInvoice');
});

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Services\ProductService;
use App\Services\CustomerInformationService;
use App\Services\TransactionService;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $productService;
    protected $CustomerInformationService;
    protected $transactionService;

    public function __construct(ProductService $productService, CustomerInformationService $customerInformationService, TransactionService $transactionService)
    {
        $this->productService = $productService;
        $this->customerInformationService = $customerInformationService;
        $this->transactionService = $transactionService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listOrder = $this->transactionService->index();
        return view('order.index', compact('listOrder'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function detail($id)
    {
        $data = $this->transactionService->show($id);
        return view('order.detail', compact('data'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = $this->transactionService->update($request);
        return response()->json(['success' => 'Post update successfully.']);
    }
}

resources/views/order/detail.blade.php
@extends('layouts.app', ['title' => 'Order | Detail'])

@section('content')
@include('components.alert-mess')
<div class="form-group">
    <div class="row">
        <div class="col-md-7" style="border-right: 1px solid;">
            <div class="row">
                <div class="col-md-6 p-2">
                    <label>Order Date</label>
                    <input type="datetime" class="form-control" name="created_at" id="created_at" value="{{ $data->created_at }}" disabled>
                </div>
                <div class="col-md-6 p-2">
                    <label>Order Number</label>
                    <input type="text" class="form-control" name="id" id="id_order" value="{{ $data->id }}" disabled>
                </div>
                <div class="col-md-6 p-2">
                    <label>Product Quantity</label>
                    <input type="number" class="form-control" name="quantity" id="quantity" value="{{ $data->quantity }}" disabled>
                </div>
                <div class="col-md-6 p-2">
                    <label>Price Detail</label>
                    <input type="text" class="form-control" name="total_money" id="total_money" value="{{ $data->total_money }}" disabled>
                </div>
                <div id="view-payment-status"class="col-md-6 p-2"></div>
                <div class="col-md-12 p-2">
                    <label>Customer Detail</label>
                    <div id="form-customer" class="form-customer">
                        <p class="m-0">- Name: {{ $data->CustomerInformation->first_name }} {{ $data->CustomerInformation->last_name }}</p>
                        <p class="m-0">- Phone: ( +{{ $data->CustomerInformation->country_code }}) {{ $data->CustomerInformation->phone }}</p>
                        <p class="m-0">- Email: {{ $data->CustomerInformation->email }}</p>
                        <p class="m-0">- Address: {{ $data->CustomerInformation->address }}</p>
                        <p class="m-0">- Suburb: {{ $data->CustomerInformation->suburb }}</p>
                        <p class="m-0">- State: {{ $data->CustomerInformation->state }}</p>
                        <p class="m-0">- Postcode: {{ $data->CustomerInformation->postcode }}</p>
                        <p class="m-0">- Country: {{ $data->CustomerInformation->country }} 
                            <button type="button" class="btn btn-outline-primary btn-sm float-end" data-bs-toggle="modal" data-bs-target="#customer_information">
                                Edit
                            </button>
                        </p>
                    </div>
                    <button id="send-mail" class="btn btn-primary float-end mt-3" type="button" onclick="sendMailInvoice('{{ $data->CustomerInformation->email }}', '{{ $data->CustomerInformation->first_name }}', '{{ $data->id }}')">Send Invoice To Customer</button>
                </div>
            </div>
        </div>
        <div id="form_order_warehouse" class="col-md-5">
            <div class="row">
                <div class="col-md-12 p-2">
                    <label>Product Name</label>
                    <input type="text" class="form-control" name="created_at" id="created_at" value="{{ $data->Product->name }}" disabled>
                </div>
                <div class="col-md-12 p-2">
                    <label>Product Code</label>
                    <input type="text" class="form-control" name="created_at" id="created_at" value="{{ $data->Product->code }}" disabled>
                </div>
                <div class="col-md-12 p-2">
                    <label>Delivery Time & Date</label>
                    <input type="datetime" class="form-control" name="delivery_at" id="delivery_at" value="{{ $data->delivery_at }}">
                </div>
                <div class="col-md-12 p-2">
                    <label>Delivery address</label>
                    <input type="datetime" class="form-control" name="delivery_address" id="delivery_address" value="{{ $data->delivery_address }}">
                </div>
                <div id="view-delivery-progress" class="col-md-12 p-2"></div>
                <div class="col-md-12 p-2">
                    <button class="btn btn-primary float-end" type="button" onclick="updateOrder()">Send Order To Warehouse</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="customer_information" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Customer Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="update-customer-form" novalidate method="POST" enctype="multipart/form-data">
                @csrf
                <input type="hidden" id="customer_id" name="customer_id" value="{{ $data->CustomerInformation->id }}">
                <div class="modal-body">
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="first_name" class="form-label">First name</label>
                            <input type="text" class="form-control" id="first_name" name="first_name" value="{{ $data->CustomerInformation->first_name }}" required>
                        </div>
                        <div class="col-sm-6">
                            <label for="last_name" class="form-label">Last name</label>
                            <input type="text" class="form-control" id="last_name" name="last_name" value="{{ $data->CustomerInformation->last_name }}" required>
                        </div>
                        <div class="col-12">
                            <label for="phone" class="form-label">Phone</label>
                            <div class="row">
                                <div class="col-md-6">
                                    <select class="form-select" id="country_code" name="country_code" required>
                                        <option value="">select country code</option>
                                        @foreach (config('option.country_codes') as $value)
                                            <option value="{{$value['id']}}" {{ $value['id'] == $data->CustomerInformation->country_code ? 'selected' : '' }}>{{$value['value']}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <input type="number" class="form-control" id="phone" name="phone" value="{{ $data->CustomerInformation->phone }}" required>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-12">
                            <label for="email" class="form-label">Email</label>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-group has-validation">
                                        <span class="input-group-text">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                                                <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
                                            </svg>
                                        </span>
                                        <input type="email" class="form-control" id="email" name="email" value="{{ $data->CustomerInformation->email }}" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                
                        <div class="col-12">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" name="address" value="{{ $data->CustomerInformation->address }}" required>
                        </div>
                
                        <div class="col-12">
                            <label for="suburb" class="form-label">Suburb</label>
                            <input type="text" class="form-control" id="suburb" name="suburb" value="{{ $data->CustomerInformation->suburb }}" required>
                        </div>
                
                        <div class="col-sm-6">
                            <label for="state" class="form-label">State</label>
                            <input type="text" class="form-control" id="state" name="state" value="{{ $data->CustomerInformation->state }}" required>
                        </div>
                
                        <div class="col-sm-6">
                            <label for="postcode" class="form-label">Postcode</label>
                            <input type="text" class="form-control" id="postcode" name="postcode" value="{{ $data->CustomerInformation->postcode }}" required>
                        </div>
                
                        <div class="col-12">
                            <label for="country" class="form-label">Country</label>
                            <select class="form-select" id="country" name="country" required>
                                <option value="">select country</option>
                                @foreach (config('option.country') as $value)
                                    <option value="{{$value['id']}}" {{ $value['id'] == $data->CustomerInformation->country ? 'selected' : '' }}>{{$value['value']}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="sumbit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    .form-customer{
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ced4da;
        background: #e9ecef;
    }
</style>
<script>
    $('#update-customer-form').submit(function(e) {
        e.preventDefault();
        let formData = new FormData(this);
        $.ajax({
            url: "{{ route('customer.update') }}",
            type: 'POST',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            data: formData,
            contentType: false,
            processData: false,
            success: function(result) {
                alert('Update customer successful!');
                location.reload();
            },
            error: function(error) {
                alert(error);
            }
        });
    });

    function sendMailInvoice(email, name, id) {
        $('#send-mail').attr('disabled','disabled');
        $.ajax({
            url: "{{ route('sendMailInvoice') }}",
            type: 'POST',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            data:  {
                email: email,
                id: id,
                name: name,
            },
            success: function(result) {
                alertSuccess('Send Mail Successfully!');
                $('#send-mail').removeAttr('disabled');
            },
            error: function(error) {
                alertError(error);
                $('#send-mail').removeAttr('disabled');
            }
        });
    }

    function updateOrder() {
        $.ajax({
            url: "{{ route('order.update') }}",
            type: 'POST',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            data:  {
                delivery_at: $('#form_order_warehouse #delivery_at').val(),
                delivery_address: $('#form_order_warehouse #delivery_address').val(),
                id: $('#id_order').val(),
            },
            success: function(result) {
                $('#view-payment-status').html(`
                    <label>Payment Status</label>
                    <input type="text" class="form-control" name="status" id="status" value="{{ config('option.status_order')[$data->status]['value'] }}" disabled>
                `);
                $('#view-delivery-progress').html(`
                    <label>Delivery Progress</label>
                    <input type="text" class="form-control" name="delivery_progress" id="delivery_progress" value="wait for confirmation" disabled>
                `);
            },
            error: function(error) {
                alertError(error);
            }
        });
    }
</script>
@endsection

resources/views/order/index.blade.php
@extends('layouts.app', ['title' => 'Order'])

@section('content')
@include('components.alert-mess')
<table class="table table-striped">
    <thead>
        <tr>
            @foreach (config('colum_table.order') as $value)
                <th scope="col">{{ $value['value'] }}</th>
            @endforeach
            <th class="col-md-1 text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($listOrder as $key => $value)
        <tr>
            <td scope="row">{{ $value->id }}</td>
            <td scope="row">{{ $value->Product->code }}</td>
            <td scope="row">{{ $value->total_money }}</td>
            <td scope="row">{{ config('option.status_order')[$value->status]['value'] }}</td>
            <td scope="row">{{ $value->created_at }}</td>
            <td class="col-md-1 text-center">
                <a class="btn btn-primary" href="{{ asset('order/detail') }}/{{$value->id}}">View</a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
{{ $listOrder->links()  }}
@endsection